/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./app/__root"
import { Route as SignupImport } from "./app/signup"
import { Route as SigninImport } from "./app/signin"
import { Route as IndexImport } from "./app/index"
import { Route as AppEditorImport } from "./app/app/_editor"
import { Route as AppInternalIndexImport } from "./app/app/internal/index"
import { Route as AppEditorIndexImport } from "./app/app/_editor/index"
import { Route as AppEditorBlocksImport } from "./app/app/_editor/blocks"
import { Route as AppEditorProjectIdImport } from "./app/app/_editor/$projectId"

// Create Virtual Routes

const AppImport = createFileRoute("/app")()

// Create/Update Routes

const AppRoute = AppImport.update({
  path: "/app",
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  path: "/signup",
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  path: "/signin",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const AppEditorRoute = AppEditorImport.update({
  id: "/_editor",
  getParentRoute: () => AppRoute,
} as any)

const AppInternalIndexRoute = AppInternalIndexImport.update({
  path: "/internal/",
  getParentRoute: () => AppRoute,
} as any)

const AppEditorIndexRoute = AppEditorIndexImport.update({
  path: "/",
  getParentRoute: () => AppEditorRoute,
} as any)

const AppEditorBlocksRoute = AppEditorBlocksImport.update({
  path: "/blocks",
  getParentRoute: () => AppEditorRoute,
} as any)

const AppEditorProjectIdRoute = AppEditorProjectIdImport.update({
  path: "/$projectId",
  getParentRoute: () => AppEditorRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/signin": {
      id: "/signin"
      path: "/signin"
      fullPath: "/signin"
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    "/signup": {
      id: "/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    "/app": {
      id: "/app"
      path: "/app"
      fullPath: "/app"
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    "/app/_editor": {
      id: "/app/_editor"
      path: "/app"
      fullPath: "/app"
      preLoaderRoute: typeof AppEditorImport
      parentRoute: typeof AppRoute
    }
    "/app/_editor/$projectId": {
      id: "/app/_editor/$projectId"
      path: "/$projectId"
      fullPath: "/app/$projectId"
      preLoaderRoute: typeof AppEditorProjectIdImport
      parentRoute: typeof AppEditorImport
    }
    "/app/_editor/blocks": {
      id: "/app/_editor/blocks"
      path: "/blocks"
      fullPath: "/app/blocks"
      preLoaderRoute: typeof AppEditorBlocksImport
      parentRoute: typeof AppEditorImport
    }
    "/app/_editor/": {
      id: "/app/_editor/"
      path: "/"
      fullPath: "/app/"
      preLoaderRoute: typeof AppEditorIndexImport
      parentRoute: typeof AppEditorImport
    }
    "/app/internal/": {
      id: "/app/internal/"
      path: "/internal"
      fullPath: "/app/internal"
      preLoaderRoute: typeof AppInternalIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  SigninRoute,
  SignupRoute,
  AppRoute: AppRoute.addChildren({
    AppEditorRoute: AppEditorRoute.addChildren({
      AppEditorProjectIdRoute,
      AppEditorBlocksRoute,
      AppEditorIndexRoute,
    }),
    AppInternalIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/signin",
        "/signup",
        "/app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/app": {
      "filePath": "app",
      "children": [
        "/app/_editor",
        "/app/internal/"
      ]
    },
    "/app/_editor": {
      "filePath": "app/_editor.tsx",
      "parent": "/app",
      "children": [
        "/app/_editor/$projectId",
        "/app/_editor/blocks",
        "/app/_editor/"
      ]
    },
    "/app/_editor/$projectId": {
      "filePath": "app/_editor/$projectId.tsx",
      "parent": "/app/_editor"
    },
    "/app/_editor/blocks": {
      "filePath": "app/_editor/blocks.tsx",
      "parent": "/app/_editor"
    },
    "/app/_editor/": {
      "filePath": "app/_editor/index.tsx",
      "parent": "/app/_editor"
    },
    "/app/internal/": {
      "filePath": "app/internal/index.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
